2023-01-18T00:14:38.500  WARN --- [-functhread3] hypercorn.error            : ASGI Framework Lifespan error, continuing without Lifespan support
2023-01-18T00:14:38.500  WARN --- [-functhread3] hypercorn.error            : ASGI Framework Lifespan error, continuing without Lifespan support
2023-01-18T00:14:38.505  INFO --- [-functhread3] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
2023-01-18T00:14:38.505  INFO --- [-functhread3] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
2023-01-18T00:14:42.322  INFO --- [   asgi_gw_0] localstack.request.http    : GET / => 200
2023-01-18T00:14:42.441  INFO --- [-functhread8] l.services.motoserver      : starting moto server on http://0.0.0.0:36471
2023-01-18T00:14:42.442  INFO --- [   asgi_gw_0] localstack.services.infra  : Starting mock S3 service on http port 4566 ...
2023-01-18T00:14:42.722  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS s3.ListObjects => 404 (404)
2023-01-18T17:13:02.496 ERROR --- [-functhread3] localstack.http.asgi       : Error while trying to schedule execution: cannot schedule new futures after shutdown with environment {'REQUEST_METHOD': 'GET', 'SCRIPT_NAME': '', 'PATH_INFO': '/_localstack/health', 'QUERY_STRING': '', 'RAW_URI': '/_localstack/health', 'REQUEST_URI': '/_localstack/health', 'SERVER_NAME': '127.0.0.1', 'SERVER_PORT': '4566', 'SERVER_PROTOCOL': 'HTTP/1.1', 'REMOTE_ADDR': '127.0.0.1', 'REMOTE_PORT': '46940', 'HTTP_HOST': 'localhost:4566', 'HTTP_USER_AGENT': 'python-requests/2.28.2', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate', 'HTTP_ACCEPT': '*/*', 'HTTP_CONNECTION': 'keep-alive', 'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.errors': <_io.BytesIO object at 0x7fbd76c71260>, 'wsgi.multithread': True, 'wsgi.multiprocess': False, 'wsgi.run_once': False, 'asgi.headers': [(b'Host', b'localhost:4566'), (b'User-Agent', b'python-requests/2.28.2'), (b'Accept-Encoding', b'gzip, deflate'), (b'Accept', b'*/*'), (b'Connection', b'keep-alive')], 'wsgi.input': <localstack.http.asgi.HTTPRequestEventStreamAdapter object at 0x7fbd99be9210>, 'wsgi.input_terminated': True}
2023-01-18T17:13:02.496 ERROR --- [-functhread3] hypercorn.error            : Error in ASGI Framework
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/asyncio/task_group.py", line 22, in _handle
    await app(scope, receive, send, sync_spawn)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/app_wrappers.py", line 31, in __call__
    await self.app(scope, receive, send)
  File "/opt/code/localstack/localstack/aws/serving/asgi.py", line 34, in __call__
    return await self.wsgi(scope, receive, send)
  File "/opt/code/localstack/localstack/http/asgi.py", line 344, in __call__
    return await self.handle_http(scope, receive, send)
  File "/opt/code/localstack/localstack/http/asgi.py", line 377, in handle_http
    iterable = await self.event_loop.run_in_executor(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 821, in run_in_executor
    executor.submit(func, *args), loop=self)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 167, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
2023-01-18T17:13:02.496 ERROR --- [-functhread3] hypercorn.error            : Error in ASGI Framework
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/asyncio/task_group.py", line 22, in _handle
    await app(scope, receive, send, sync_spawn)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/app_wrappers.py", line 31, in __call__
    await self.app(scope, receive, send)
  File "/opt/code/localstack/localstack/aws/serving/asgi.py", line 34, in __call__
    return await self.wsgi(scope, receive, send)
  File "/opt/code/localstack/localstack/http/asgi.py", line 344, in __call__
    return await self.handle_http(scope, receive, send)
  File "/opt/code/localstack/localstack/http/asgi.py", line 377, in handle_http
    iterable = await self.event_loop.run_in_executor(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 821, in run_in_executor
    executor.submit(func, *args), loop=self)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 167, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
